### ISSUE TITLE
Cannot import this package with rn 0.76.0 and jdk 17

### ISSUE THREAD

**Issue by JeffreyZhu0201** [ccnnde/react-native-simple-openvpn#71]
**Bug description:**

Cannot import this package with rn 0.76.0 and jdk 17

**Environment:**
 - OS:win
 - OS version:
 - react-native version: 0.76.0
 - react-native-simple-openvpn version: 2.1.2

## after yarn android:

```
> Task :vpnLib:compileUiDebugJavaWithJavac FAILED
71 actionable tasks: 49 executed, 22 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\com\android\vending\billing\IInAppBillingService.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl10626258024024460075.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\com\android\vending\billing\IInAppBillingService.aidl


                                                   ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\com\android\vending\billing\IInAppBillingService.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl10626258024024460075.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\com\android\vending\billing\IInAppBillingService.aidl




       ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\com\android\vending\billing\IInAppBillingService.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl10626258024024460075.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\com\android\vending\billing\IInAppBillingService.aidl





                                                                                ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\ExternalCertificateProvider.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl10552202333704445814.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\ExternalCertificateProvider.aidl


                                                   ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\ExternalCertificateProvider.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl10552202333704445814.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\ExternalCertificateProvider.aidl




       ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\ExternalCertificateProvider.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl10552202333704445814.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\ExternalCertificateProvider.aidl





                                                                                ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\IOpenVPNAPIService.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl13496521589772126316.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\IOpenVPNAPIService.aidl


                                                   ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\IOpenVPNAPIService.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl13496521589772126316.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\IOpenVPNAPIService.aidl




       ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\IOpenVPNAPIService.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl13496521589772126316.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\IOpenVPNAPIService.aidl





                                                                                ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\IOpenVPNStatusCallback.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl17660988899180612330.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\IOpenVPNStatusCallback.aidl


                                                   ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\IOpenVPNStatusCallback.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl17660988899180612330.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\IOpenVPNStatusCallback.aidl




       ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\api\IOpenVPNStatusCallback.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl17660988899180612330.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\api\IOpenVPNStatusCallback.aidl





                                                                                ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\core\IOpenVPNServiceInternal.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl8874941485075247091.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\core\IOpenVPNServiceInternal.aidl


                                                   ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\core\IOpenVPNServiceInternal.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl8874941485075247091.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\core\IOpenVPNServiceInternal.aidl




       ^
D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\core\IOpenVPNServiceInternal.java:3: ����: �Ƿ��� Unicode ת��
 * Using: C:\Users\JeffreyZhu\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe -pC:\Users\JeffreyZhu\AppData\Local\Android\Sdk\platforms\android-35\framework.aidl -oD:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -ID:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\0cae9777d78a11e62cca32e1297ef73a\transformed\core-1.6.0\aidl -IC:\Users\JeffreyZhu\.gradle\caches\8.10.2\transforms\676456ad6d15bcb3fc262052291325ad\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\JEFFRE~1\AppData\Local\Temp\aidl8874941485075247091.d D:\CODE\Github\RN\AwesomeProject\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\core\IOpenVPNServiceInternal.aidl

```

**Comment by JeffreyZhu0201** [comment]
i cant use react-native link on 0.76

**Comment by ccnnde** [comment]
This issue does not exist on macOS. I will test it on Windows 10 later to see.

**Comment by ccnnde** [comment]
The issue has been reproduced in Windows 10

First, the output error contains garbled characters. You need to set the language to English in `android\gradle.properties`

```diff
-org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
+org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Duser.language=en -Duser.country=US
```

Then, re-run the build, and you will see the following error: **illegal unicode escape**

```
> Task :vpnLib:compileUiDebugJavaWithJavac FAILED
56 actionable tasks: 6 executed, 50 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

D:\XXX\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\com\android\vending\billing\IInAppBillingService.java:3: error: illegal unicode escape
 * Using: C:\Users\xxx\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe...
```

Next, open the location of the error, you will see the following content

```java
/*
 * This file is auto-generated.  DO NOT MODIFY.
 * Using: C:\Users\xxx\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe...
 */
package com.android.vending.billing;
// ...
```

It is this path `Using: C:\Users\xxx\AppData\Local\Android\Sdk\build-tools\35.0.0\aidl.exe...` that caused the build failure

Please modify `android\build.gradle` for a temporary solution, then the automatically generated comments will not include that path

```diff
buildscript {
    ext {
-       buildToolsVersion = "35.0.0"
+       buildToolsVersion = "34.0.0"
        minSdkVersion = 24
        compileSdkVersion = 35
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.24"
    }
}
```

**Comment by JeffreyZhu0201** [comment]
Can you write a tutorial to configure the environment on windows, including the java version, configuration, SDK installation, react-native version, because I keep building failed

**Comment by ccnnde** [comment]
Just configure it according to this. https://reactnative.cn/docs/environment-setup

The React Native version is also 0.76.

**Comment by JeffreyZhu0201** [comment]
BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create an instance of type com.android.build.api.variant.impl.ApplicationVariantImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at makeError (D:\CODE\Github\RN\react-native-simple-openvpn\example\node_modules\execa\index.js:174:9)
    at D:\CODE\Github\RN\react-native-simple-openvpn\example\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async runOnAllDevices (D:\CODE\Github\RN\react-native-simple-openvpn\example\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\CODE\Github\RN\react-native-simple-openvpn\example\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by JeffreyZhu0201** [comment]
I set the right env and still build failed,please save me.

**Comment by ccnnde** [comment]
The example that comes with the project is too outdated. Please initialize a new RN project and try configuring it according to the README.

**Comment by JeffreyZhu0201** [comment]
Thanks a lot,I already solved  this problem!


> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_XL_API_35(AVD) - 15' for :app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 5s
104 actionable tasks: 14 executed, 90 up-to-date
info Connecting to the development server...
8081
info Starting the app on "emulator-5554"...
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.awesomeproject/.MainActivity }
Done in 11.18s.
